import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import { motion } from "framer-motion";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navigation />
      
      <main className="container mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16 flex-grow">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="max-w-3xl mx-auto"
        >
          <h1 className="text-4xl font-display font-bold mb-8">Privacy Policy</h1>
          
          <div className="prose prose-slate dark:prose-invert max-w-none space-y-6">
            <section>
              <h2 className="text-2xl font-display font-bold mb-4">AI-Generated Content</h2>
              <p className="text-muted-foreground leading-relaxed">
                Please be aware that all articles, images, and content displayed on HotOnNet are generated by artificial intelligence. This platform is a demonstration of automated content curation and digital journalism.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display font-bold mb-4">Introduction</h2>
              <p className="text-muted-foreground leading-relaxed">
                At HotOnNet, we take your privacy seriously. This Privacy Policy explains how we collect, use, and protect your personal information when you use our website.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display font-bold mb-4">Information We Collect</h2>
              <p className="text-muted-foreground leading-relaxed">
                We may collect personal information such as your name and email address when you interact with our site, subscribe to our newsletter, or contact us.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display font-bold mb-4">How We Use Your Information</h2>
              <p className="text-muted-foreground leading-relaxed">
                We use the information we collect to provide and improve our services, communicate with you, and personalize your experience on HotOnNet.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display font-bold mb-4">Data Security</h2>
              <p className="text-muted-foreground leading-relaxed">
                We implement a variety of security measures to maintain the safety of your personal information. However, no method of transmission over the Internet is 100% secure.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display font-bold mb-4">Changes to This Policy</h2>
              <p className="text-muted-foreground leading-relaxed">
                We may update our Privacy Policy from time to time. Any changes will be posted on this page with an updated revision date.
              </p>
            </section>

            <section>
              <p className="text-sm text-muted-foreground italic">
                Last updated: January 12, 2026
              </p>
            </section>
          </div>
        </motion.div>
      </main>

      <Footer />
    </div>
  );
}
